version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: bakerydb_dev
    environment:
      POSTGRES_DB: bakerydb
      POSTGRES_USER: sysuser
      POSTGRES_PASSWORD: bakerydev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: